export const ComingSoon = {
  position: 'relative',
  overflow: 'hidden',
  pointerEvents: 'none',
  minWidth: '10ch',
  minHeight: '5ch',
  ':before': {
    pointerEvents: 'auto',
    content: '""',
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    zIndex: 999999,
    background: 'document 0.9',
  },
  Span: {
    extends: 'Flex',
    flow: 'y',
    position: 'absolute',
    transform: 'translate3d(-50%, -50%, 1px)',
    top: '50%',
    left: '50%',
    zIndex: '999999 + 1',
    whiteSpace: 'nowrap',
    lineHeight: 1.1,
    fontWeight: 'bold',
    color: 'diasbled',
    textTransform: 'uppercase',
    fontSize: 'X2',
    align: 'center center',
    Strong: {
      extends: 'Flex',
      align: 'center',
      text: 'Branching',
    },
    Span: {
      fontWeight: 'normal',
      text: 'Coming soon',
    },
  },
};