export const ModalWindow = {
  tag: 'section',
  state: {},
  theme: 'modal',
  padding: 'A B',
  round: 'A',
  gap: 'C',
  flow: 'column',
  overflow: 'auto',
  width: 'fit-content',
  height: 'fit-content',
  animationDuration: 'C',
  position: 'relative',
  IconButton: {
    icon: 'crossmark',
    padding: 'Y2',
    position: 'absolute',
    top: 'Z2',
    right: 'Z2',
    color: 'dim',
    onClick: (ev, el, s, ctx) => el.call('closeModal'),
  },
  ModalHeader: {},
};